### ISSUE TITLE
Shift modifer bind not properly working with 

### ISSUE THREAD

**Issue by dabadoo** [kapresoft/wow-addon-actionbar-plus#325] opened 2023-08-21 18:32 UTC
**Describe the bug**
Binds made using a shift modfier such as: "Shift-H" sometimes don't work on keypress down and only responds to keypress up.
Sometimes they do work. Sometimes they don't.

Maybe an issue related to solution for:

#26 
#27

**Comment by dabadoo** [comment] 2023-08-21 18:36
Some more testing:

Pressing a bind that's NOT a shift bind will still sometimes not work while pressing shift and the bind.
Example: I press F to Nature's Swiftness. On blizzard bars, if I held shift while pressing F, it would still use my F bind since nothing else is bound to it. Keydown works without issue.
When having bound F on a ABP bar it still works whether or not I hold shift while pressing F, BUT it doesn't always trigger on keyDown as it should.

**Comment by dabadoo** [comment] 2023-08-21 20:02
I can make changes that fixes my keybinds to work with shift on keydown but then shift-clicking to move breaks and starts using items on Keydown when trying to drag with mouse.

**Comment by dabadoo** [comment] 2023-08-21 21:43
These changes have sort fixed all my issues and I have only found 1 negative.

local function RegisterForClicks(widget, event, down)
    local useKeyDown = GetCVarBool("ActionButtonUseKeyDown")
    local btn = widget.button()
    if E.ON_LEAVE == event then
        if useKeyDown then
            btn:RegisterForClicks('AnyDown')
        else
            btn:RegisterForClicks('AnyUp')
        end
    elseif E.ON_ENTER == event then
        if useKeyDown then
            --- Note: Macro will not trigger on first click if Drag Key is used in 'mod:<key>' in macros
            --- Macros should not use mod:<key> on the same drag key
            btn:RegisterForClicks('KeyUp' or 'KeyDown')
        else
            btn:RegisterForClicks('AnyUp')
        end
    elseif 'PreClick' == event or 'PostClick' == event then
        if useKeyDown then
            btn:RegisterForClicks(KeyDown and WMX:IsDragKeyDown() and 'AnyUp' or 'AnyDown')
        else
            btn:RegisterForClicks('AnyUp')
        end
    end
end

----

When changing to this. All modifier binds works on keydown. Dragging no longer results in accidentally using items/cds.
ONLY ISSUE I'VE FOUND: Taking my bind shift-H as an example again. If I hover my mouse over the shift-H actionbarplus button and then press shift+H on my keyboard, it doesn't work. Placing my cursor over shift-H and pressing a different bind works fine.
Personally not an issue for me, but maybe this is a deal breaker for others.

**Comment by kapresoft** [comment] 2024-01-26 20:31
Hi There,
Please give this another try and see if it is fixed on #344.

**Comment by dabadoo** [comment] 2024-01-28 09:31
Tried latest version but the issue still persist.

**Comment by nfet** [comment] 2024-03-27 23:35
I'm able to repro this on Retail:

### Repro steps:

1. Bind and action "Shift + key" and "Control + key" (same key)
2. Drag and drop a spell into the same action slot
3. Press Control + key (works as expected)
4. Press Shift + key (I have to press 1+ consecutively) for it to trigger
4a. On a real spell, it may instantly work afterwards
4b. On a macro like `/cast <spell>`, it consistently behaves bad (2+ consecutive clicks) for it to trigger

### Expected Behavior:
Action button triggers "On Keydown" without delay

**Comment by nfet** [comment] 2024-03-30 04:50
Here's an update:  I have this fixed for all versions WOTLK, Retail and classic era. Just running regressions on the new code now to be sure. Will check-in and release in about a day or two.

**Comment by dabadoo** [comment] 2024-03-30 21:41
@nfet 
Quick test on SoD Classic.

At first it seemed to work. Pressing Shift-H worked on keydown.
I tried moving and spamming random buttons for a bit and suddenly it no longer works. I press shift-H and now it doesn't activate until key up.

Even bigger issue: The moment I press shift down the entire game freezes for a second then unfreezes again. Releasing shift doesn't cause any issue.

**Comment by dabadoo** [comment] 2024-03-30 21:48
Some more info but don't know how useful it will be:
1. Logged on a level 1 char and disabled all addons except this one. No issues with pressing shift.
2. Changed to my main profile. Started freezing when pressing shift.
3. Changed back to the default profile and the issue was gone.

**Comment by nfet** [comment] 2024-03-30 23:30
That is so sad. I have archived that version (2024.3.7) from curseforge for now while I investigate.  I will try and reproduce with a clean profile then with an existing profile. 

Thank you for verifying.  You are sincerely appreciated.

Also for the standard WoW Action Button behavior, I just wanted to confirm that you are getting the same standard behavior.  The following details is what I experience in WoW actionbars.   

### Here's an example screenshot for visual aid

![image](https://github.com/kapresoft/wow-addon-actionbar-plus/assets/1599306/91dd441c-0a30-4134-b24f-86d97fbd537d)

For this purpose, let's say I have priest class with Renew on Blizzard Actionbar1 slot 1 (keyboard shortcut 1).

### 1.  "Lock Action Bars" is checked

#### Keypress Behavior
- When 1 is pressed, Renew will trigger on keydown
- When the modifier key and 1 (i.e. SHIFT + 1) is held down, then the actionbutton triggers on keyup. This is because it also trigger the "unlock actionbar"  feature so that the spell won't trigger on mouse drag.

#### Mouse Click Behavior
- When clicking the  WoW action button, Renew always triggers on mouseup.  This is different from ActionbarPlus, where Renew will trigger on mousedown unless the modifier key is pressed, where it then triggers on keyup.

### 2.  "Lock Action Bars" is not checked (disabled)

#### Keypress Behavior
- When 1 is pressed, Renew will now trigger on **keyup**.  This is so that the action will not trigger on mouse drag.

#### Mouse Click Behavior
- Same as Keypress Behavior, triggers on **keyup** 

## ActionbarPlus action buttons behavior
ABP will esssentially behave (should behave) the same way except  it will trigger on mousedown when an action is pressed. This is what I'm aiming for anyways.  Also, for retail, it doesn't support the "lock and hold down" action.

**Comment by nfet** [comment] 2024-03-30 23:43
I think for this part, it's conditional.  Please see my recent message on the button behavior.
If the "modifier key" + key is pressed, then action triggers on key-up.  Holding the modifier key triggers the "unlock actionbar" so that the action can be clicked and dragged.

I disabled all the addons and the blizzard actionbars always triggers on keyup/mouseup.  The side-effect of having actionbarplus enabled is that the mouse click triggers on keydown :-).

> ### Expected Behavior:
> Action button triggers "On Keydown" without delay

Also, I disabled all the addons except the debug addons and I couldn't reproduce the freeze on an existing actionbarplus profile.  The "Addon Usage" addon reported only CPU usage of 1.5.  This doesn't really take ABP off the hook but I will keep investigating.

![image](https://github.com/kapresoft/wow-addon-actionbar-plus/assets/1599306/570b2518-7aac-4eae-8c2f-47cbb319ffba)


> I'm able to repro this on Retail:
> 
> ### Repro steps:
> 1. Bind and action "Shift + key" and "Control + key" (same key)
> 2. Drag and drop a spell into the same action slot
> 3. Press Control + key (works as expected)
> 4. Press Shift + key (I have to press 1+ consecutively) for it to trigger
>    4a. On a real spell, it may instantly work afterwards
>    4b. On a macro like `/cast <spell>`, it consistently behaves bad (2+ consecutive clicks) for it to trigger
> 
> ### Expected Behavior:
> Action button triggers "On Keydown" without delay

**Comment by nfet** [comment] 2024-03-30 23:52
For this part this is the correct behavior if "shift" is the assigned modifier key.

> I press shift-H and now it doesn't activate until key up.

**Comment by nfet** [comment] 2024-03-30 23:57
> Some more info but don't know how useful it will be:
> 
> 1. Logged on a level 1 char and disabled all addons except this one. No issues with pressing shift.
> 2. Changed to my main profile. Started freezing when pressing shift.
> 3. Changed back to the default profile and the issue was gone.

Please let me know if this version is OK to be up on CurseForge, otherwise I will have to revert to the old behavior.  I like this change now because it is consistent with all versions of WoW, but I don't want to risk potential bad freezing experience to others.  Thank you again.

**Comment by nfet** [comment] 2024-03-31 00:02
Here's the priest macro I tested with on SoD:

Keybind:  ]
> shift + ] or ctrl + ] is not keybinded, just ] (right square bracket)

```
/cast [harm] Shadow Word: Pain; [mod:ctrl] Lesser Heal; [mod:shift] Penance; Renew
```

**Comment by nfet** [comment] 2024-03-31 00:39
Just note to self here.  Upon initial investigation Addon Usage did not show any CPU or memory spike.  For this reason, I need more details on how to repro, so I made version 2024.3.7 active again on Curse Forge in the hope that someone will run into this issue and get another detail on this.

The work around is that the user/player can revert to the older version.

**Comment by dabadoo** [comment] 2024-03-31 08:46
> 1. "Lock Action Bars" is checked
Keypress Behavior
    

> When 1 is pressed, Renew will trigger on keydown (EDIT: If all addons are disabled, this will trigger on keyup). ActionbarPlus changed this behavior.)

> When the modifier key and 1 (i.e. SHIFT + 1) is held down, then the actionbutton triggers on keyup. This is because it also trigger the "unlock actionbar" feature so that the spell won't trigger on mouse drag.

For me when I disable all addons, use default blizzard actionbars and have locked them with shift key enabled to drag.
1. When 2 is pressed Lesser Heal triggers on keydown
2. When the modifier key and 2 (i.e. SHIFT + 2) is held down my actionbutton still triggers on keydown.

I tried deleting my account#1 config-cache and got same results as my previous testing.

I tried testing the behaivior again with only this addon enabled and Lesser heal placed on default actionbars.
1. When 2 is pressed Lesser Heal triggers on keydown
2. When the modifier key and 2 (i.e. SHIFT + 2) is held down my actionbutton now triggers on keyup.
----
I did some test with addonusage enabled and commented on my findings.
https://imgur.com/a/vdAKXvL
----
Would it help if I gave you my profile?
https://pastebin.com/x7i2c5gu
The name of the profile causing issues is the "MyDefault" The binded macro I've been using, placed on the addon, is Shift-H for the macro "/use Supercharged Chronoboon Displacer\n/use Chronoboon Displacer\n"

**Comment by nfet** [comment] 2024-03-31 18:03
Thanks for the Addon Usage details and images.  This will get me far.  Seems like ABP is not playing nice with others.  No need to get your profile for now.  I'll will try to repro.

Cheers,

**Comment by nfet** [comment] 2024-03-31 19:52
OK, I found a solution that makes all version happy.  Just running regressions now.  Should be released by today.

**Closed** 2024-04-01 00:09 UTC
Labels: Bug, Priority: High

**Comment by nfet** [comment] 2024-04-01 00:13
Give this new version a try (2024.3.8) when you can.  I'll add more details on the fix in a bit.

https://legacy.curseforge.com/wow/addons/actionbarplus/files/5226102

**Comment by dabadoo** [comment] 2024-04-01 07:17
Testing on SoD. Macro is not working when Shift-H pressed down.

The Freeze issue is much better. No longer getting second long freezes but there still seems to be some observable stuttering every time I press shift.

https://imgur.com/a/bCMXOCH

Spamming shift and nothing else still makes the addon shoot up in memory and cpu usage.

**Comment by nfet** [comment] 2024-04-01 07:45
The cpu and mem are at the acceptable range. I will keep optimizing. But for the rest of the issues I am out of options at this point. I will have to get back to this sometime in the future. I apologize for the inconvenience.
